### ISSUE TITLE
installation issue: AttributeError: '_Environ' object has no attribute 'has_key':

### ISSUE THREAD

**Issue by hafizmtalha** [egaffo/CirComPara#8]
hi, I am trying to install CirComPara but facing this issue during installation:
scons: Reading SConscript files ...
AttributeError: '_Environ' object has no attribute 'has_key':
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/src/ccp_install_tools.scons", line 18:
    if not env['ENV'].has_key('VIRTUAL_ENV'):

**Comment by egaffo** [comment]
Which Python version are you running?
Mind that you must use Python2.7. Python 3 is not supported (several reasons prevented me from updating the Python version).
As it is an old Python version, you may consider virtualenv to get a python2.7 sandbox.

**Comment by hafizmtalha** [comment]
Thanks.. that helped I was working on python 3.7
but now It's installed but new error..
TypeError: Tried to lookup Dir 'ccp_dbs/ccp_indexes' as a File:
File "/media/alphagenomics/Bay2/Softwares/CirComPara/src/ccp_main.scons", line 356:
    exports = '''env_check_indexes''')
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/tools/scons/scons-local-3.1.2/SCons/Script/SConscript.py", line 660:
    return method(*args, **kw)
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/tools/scons/scons-local-3.1.2/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/tools/scons/scons-local-3.1.2/SCons/Script/SConscript.py", line 286:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/src/ccp_check_indexes.scons", line 117:
    exports = '''env_build_indexes ''')
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/tools/scons/scons-local-3.1.2/SCons/Script/SConscript.py", line 660:
    return method(*args, **kw)
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/tools/scons/scons-local-3.1.2/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/tools/scons/scons-local-3.1.2/SCons/Script/SConscript.py", line 286:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/src/ccp_build_indexes.scons", line 60:
    env_index_hisat2['GENOME'] = ','.join([File(f).abspath for f in env['GENOME'].split(',')])
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/tools/scons/scons-local-3.1.2/SCons/Script/SConscript.py", line 660:
    return method(*args, **kw)
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/tools/scons/scons-local-3.1.2/SCons/Environment.py", line 2092:
    return self.fs.File(s, *args, **kw)
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/tools/scons/scons-local-3.1.2/SCons/Node/FS.py", line 1382:
    return self._lookup(name, directory, File, create)
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/tools/scons/scons-local-3.1.2/SCons/Node/FS.py", line 1361:
    return root._lookup_abs(p, fsclass, create)
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/tools/scons/scons-local-3.1.2/SCons/Node/FS.py", line 2406:
    result.must_be_same(klass)
  File "/media/alphagenomics/Bay2/Softwares/CirComPara/tools/scons/scons-local-3.1.2/SCons/Node/FS.py", line 618:
    (self.__class__.__name__, self.get_internal_path(), klass.__name__))

**Comment by egaffo** [comment]
Could you paste your vars.py and meta.csv?
It seems CirComPara2 cannot generate the genome index files. 
Perhaps there is an error in the genome sequence file path?

**Comment by hafizmtalha** [comment]
m using the test files for this.. I have posting these files bellow
##meta.csv
file,sample,condition
test_circompara/reads/readsA_1.fq,S1,WT
test_circompara/reads/readsA_2.fq,S1,WT
test_circompara/reads/readsB_1.fq,S2,MU
test_circompara/reads/readsB_2.fq,S2,MU

##vars.py
META            = 'meta.csv'
GENOME_FASTA    = '../annotation/CFLAR_HIPK3.fa'
ANNOTATION      = '../annotation/CFLAR_HIPK3.gtf' 
CPUS            = '4'
PREPROCESSOR    = 'trimmomatic'
PREPROCESSOR_PARAMS = 'MAXINFO:40:0.5 LEADING:20 TRAILING:20 SLIDINGWINDOW:4:30 MINLEN:35 AVGQUAL:30'
CIRCRNA_METHODS = 'dcc,ciri,findcirc,testrealign,'\
                  'circexplorer2_star,circexplorer2_segemehl,'\
                  'circexplorer2_bwa,circexplorer2_tophat,circrna_finder'

TOGGLE_TRANSCRIPTOME_RECONSTRUCTION = 'False'
FIX_READ_HEADER = 'True'
#MIN_READS = 2 #default

## aligners' custom parameters
HISAT2_EXTRA_PARAMS = '--rna-strandness RF' # stranded libraries
## parameters from CIRI
BWA_PARAMS = ['-T', '19', '-c', '1']
## parameters from CIRCexplorer2
SEGEMEHL_PARAMS = ['-M','1'] #'-D', '0', '-Z', '20'
TOPHAT_PARAMS = ['--max-multihits', '1']#'--zpacker','pigz' 
## parameters used in DCC manual example
STAR_PARAMS = ['--outFilterMultimapNmax', '1', 
               '--outSJfilterOverhangMin', '15', '15', '15', '15',
               '--alignSJoverhangMin', '15',
               '--alignSJDBoverhangMin', '15',
               '--seedSearchStartLmax', '30',
               '--outFilterScoreMin', '1',
               '--outFilterMatchNmin', '1',
               '--outFilterMismatchNmax', '2',
               '--chimSegmentMin', '15',
               '--chimScoreMin', '15',
               '--chimScoreSeparation', '10',
               '--chimJunctionOverhangMin', '15'] 

## pre-computed index and annotation files 
#GENOME_INDEX = "../indexes/hisat2/CFLAR_HIPK3"
#SEGEMEHL_INDEX = "../indexes/segemehl/CFLAR_HIPK3.idx"
#BWA_INDEX = "../indexes/bwa/CFLAR_HIPK3"
#BOWTIE2_INDEX = "../indexes/bowtie2/CFLAR_HIPK3"
#BOWTIE_INDEX = "../indexes/bowtie/CFLAR_HIPK3"
#STAR_INDEX = "../indexes/star/CFLAR_HIPK3"
#GENEPRED = "../annotation/CFLAR_HIPK3.genePred.wgn"

LIN_COUNTER = 'ccp' #'dcc'

DCC_EXTRA_PARAMS = ['-fg', '-M', '-Nr', 1, 1, '-F', '-ss']
TESTREALIGN_PARAMS = ['-q', 'median_1'] ## suggested 'median_40'
CE2_PARAMS = ['--no-fix'] #suggested not to set '--no-fix' in real datasets
FINDCIRC_EXTRA_PARAMS = ['--best-qual', '0'] #suggested '40' 
FIX_READ_HEADER = 'True'
SAM_SORT_MM = '1G'
#BYPASS = 'linear'

**Comment by egaffo** [comment]
I've just realized you are posting in the old version of CirComPara!
Please, use the new CirComPara2 (https://github.com/egaffo/circompara2). 
Many issues have been fixed there and I no longer support this repo.
